import sys

INF = sys.maxsize

HOT_KEY_QUIT = "q"
HOT_KEY_MINO_ROTATE_CW = "up"
HOT_KEY_MINO_MOVE_DOWN = "down"
HOT_KEY_MINO_MOVE_RIGHT = "right"
HOT_KEY_MINO_MOVE_LEFT = "left"

HOT_KEY_LIST = [
    HOT_KEY_QUIT,
    HOT_KEY_MINO_ROTATE_CW,
    HOT_KEY_MINO_MOVE_DOWN,
    HOT_KEY_MINO_MOVE_RIGHT,
    HOT_KEY_MINO_MOVE_LEFT,
]

BOARD_WIDTH = 10
BOARD_HEIGHT = 20
GAME_LOOP_TRIGGER_TIME = 0.07
